-- Enable pgvector extension for vector similarity search
CREATE EXTENSION IF NOT EXISTS vector;

-- Add embedding column to code_civil_articles table
-- Mistral Embed API produces 1024-dimensional vectors
ALTER TABLE public.code_civil_articles
ADD COLUMN IF NOT EXISTS embedding vector(1024);

-- Create an index for fast vector similarity search
-- Using HNSW (Hierarchical Navigable Small World) algorithm for approximate nearest neighbor search
-- cosine distance is the similarity metric
CREATE INDEX IF NOT EXISTS idx_code_civil_articles_embedding
ON public.code_civil_articles
USING hnsw (embedding vector_cosine_ops);

-- Create a function to search for similar articles based on embedding
CREATE OR REPLACE FUNCTION search_similar_articles(
  query_embedding vector(1024),
  match_threshold float DEFAULT 0.7,
  match_count int DEFAULT 5
)
RETURNS TABLE (
  id uuid,
  article_number text,
  title text,
  content text,
  category text,
  similarity float
)
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  SELECT
    code_civil_articles.id,
    code_civil_articles.article_number,
    code_civil_articles.title,
    code_civil_articles.content,
    code_civil_articles.category,
    1 - (code_civil_articles.embedding <=> query_embedding) AS similarity
  FROM public.code_civil_articles
  WHERE code_civil_articles.embedding IS NOT NULL
    AND 1 - (code_civil_articles.embedding <=> query_embedding) > match_threshold
  ORDER BY code_civil_articles.embedding <=> query_embedding
  LIMIT match_count;
END;
$$;

-- Create an index on article_number for faster lookups
CREATE INDEX IF NOT EXISTS idx_code_civil_articles_article_number
ON public.code_civil_articles(article_number);

-- Comment on the new column
COMMENT ON COLUMN public.code_civil_articles.embedding IS
'Vector embedding of the article content generated by Mistral Embed API (1024 dimensions)';

-- Comment on the search function
COMMENT ON FUNCTION search_similar_articles IS
'Search for similar articles based on vector similarity using cosine distance. Returns articles with similarity above threshold, ordered by relevance.';
